spring.application.name=ch14-spring-boot-data-presistence
spring.datasource.url=jdbc:mysql://localhost:3306/spring_learning
spring.datasource.username=root
spring.datasource.password=Sgdk11@2007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver