spring.application.name=ch11-spring-boot-consuming-rest-endpoints
spring.datasource.url=jdbc:mysql://localhost:3306/spring_learning
spring.datasource.username=root
spring.datasource.password=Sgdk11@2007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true