spring.application.name=ch12-spring-boot-data-sources
# The connection URL (ensure the database name matches your MySQL setup)
spring.datasource.url=jdbc:mysql://localhost:3306/spring_learning

# Your MySQL credentials
spring.datasource.username=root
spring.datasource.password=Sgdk11@2007

# The driver class for MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
